mapping = (
    u"ཀཁགངཅཆཇཉཏཐདནཔཕབམཙཚཛཝཞཟའཡརལཤསཧཨ་", u"kakhagangachachhajanyatathadanapaphabamatsatshadzawazhazazyaralashasahaa-"
)
pre_processor_mapping = {
    # Dzongkha Index Characters
    u"ཀ": u"ka",
    u"ཁ": u"kha",
    u"ག": u"ga",
    u"ང": u"nga",
    u"ཅ": u"cha",
    u"ཆ": u"chha",
    u"ཇ": u"ja",
    u"ཉ": u"nya",
    u"ཏ": u"ta",
    u"ཐ": u"tha",
    u"ད": u"da",
    u"ན": u"na",
    u"པ": u"pa",
    u"ཕ": u"pha",
    u"བ": u"ba",
    u"མ": u"ma",
    u"ཙ": u"tsa",
    u"ཚ": u"tsha",
    u"ཛ": u"dza",
    u"ཝ": u"wa",
    u"ཞ": u"zha",
    u"ཟ": u"za",
    u"འ": u"z",
    u"ཡ": u"ya",
    u"ར": u"ra",
    u"ལ": u"la",
    u"ཤ": u"sha",
    u"ས": u"sa",
    u"ཧ": u"ha",
    # Subjoined letters (Main characters)
#    u"ྱ": u"ya",
#    u'ྭ': u"wa",
#    u"ྐ": u"ka",
#    u"ྒ": u"ga",
#    u"ྲ": u"ra",
#    u"ྟ": u"ta",
#    u"ྤ": u"pa",
#    u"ྨ": u"ma",
#    u"ླ": u"la",
#    u"ྩ": u"tsa",
#    u"ྗ": u"ja",
#    u"ྣ": u"na",
#    u"ཊ": u"tta",
#    u"ྚ": u"tta",
#    u"ྙ": u"nya",
#    u"ཌ": u"dda",
#    u"ྜ": u"dda",
#    # Subjoined letters (https://scriptsource.org/cms/scripts/page.php?item_id=wrSys_detail_sym&key=dz-Tibt)
#    u"ྑ": u"kha",
#    u"ྔ": u"nga",
#    u"ྠ": u"tha",
#    u"ྡ": u"da",
#    u"ྥ": u"pha",
#    u"ྦ": u"ba",
#    u"ྪ": u"tsha",
#    u"ྫ": u"dza",
#    u"ྵ": u"ssa",
#    u"ྶ": u"sa",
#    u"ྷ": u"ha",
#    u"ྛ": u"ttha",
#    u"ཎ": u"nna",
#    u"ྞ": u"nna",
#    u"ྺ": u"wa",
#    u"ྻ": u"ya",
#    u"ྼ": 'ra',
#    # Vowels
    u"ཨ": u"a",
    u"ཱ": u"aa",
    u"ཨད": u"ay",
    u"ཨན": u"ay",
    u"ཨའ": u"ay",
    u"ཨས": u"ay",
    u"ེ": u"e",
    u"ཻ": u"ee",
    u"ི": u"i",
    u"ུ": u"u",
    u"ུད": u"ue",
    u"ུན": u"ue",
    u"ུའ": u"ue",
    u"ུས": u"ue",
    u"ོ": u"o",
    u"ཽ": u"oo",
    u"ོད": u"oe",
    u"ོན": u"oe",
    u"ོའ": u"oe",
    u"ོས": u"oe",
    u"྄": u"halanta",
    # Dzongkha numerals
    u"༠": u"legkor",
    u"༡": u"chi",
    u"༢": u"nyi",
    u"༣": u"sum",
    u"༤": u"zhi",
    u"༥": u"nga",
    u"༦": u"dru",
    u"༧": u"duen",
    u"༨": u"gay",
    u"༩": u"gu",
    u"༡༠": u"chu tham",
    u"༡༡": u"chu-chi",
    u"༡༢": u"chu-ni",
    u"༡༣": u"chu-sum",
    u"༡༤": u"chu-zi",
    u"༡༥": u"che-nga",
    u"༡༦": u"chu-du",
    u"༡༧": u"chup-dü",
    u"༡༨": u"chop-gay",
    u"༡༩": u"chü-gu",
    u"༢༠": u"khe chi",
    u"༢༡": u"nyer chi",
    u"༢༢": u"nyer nyi",
    u"༢༣": u"nyer sum",
    u"༢༤": u"nyer zhi",
    u"༢༥": u"nyer nga",
    u"༢༦": u"nyer dru",
    u"༢༧": u"nyer duen",
    u"༢༨": u"nyer gay",
    u"༢༩": u"nyer gu",
    # Punctuation marks
    u"་": u"-",
    u"?": u"?",
    u"།": u".",
}